package com.blueseaheart.core.dao;

import com.blueseaheart.core.domain.PKECHx;
import com.blueseaheart.core.domain.PKECHxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PKECHxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int countByExample(PKECHxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer hxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int insert(PKECHx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int insertSelective(PKECHx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    List<PKECHx> selectByExample(PKECHxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    PKECHx selectByPrimaryKey(Integer hxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PKECHx record, @Param("example") PKECHxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PKECHx record, @Param("example") PKECHxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PKECHx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PKECHx record);
}