package com.blueseaheart.core.domain;

import java.util.Date;

public class CoreUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_married
     *
     * @mbggenerated
     */
    private Integer userMarried;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_id_no
     *
     * @mbggenerated
     */
    private String userIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_second_phone
     *
     * @mbggenerated
     */
    private String userSecondPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_urgent_phone
     *
     * @mbggenerated
     */
    private String userUrgentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_create_time
     *
     * @mbggenerated
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_update_time
     *
     * @mbggenerated
     */
    private Date userUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_comment
     *
     * @mbggenerated
     */
    private String userComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_status
     *
     * @mbggenerated
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_user.user_deleted
     *
     * @mbggenerated
     */
    private Integer userDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_id
     *
     * @return the value of core_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_id
     *
     * @param userId the value for core_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_name
     *
     * @return the value of core_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_name
     *
     * @param userName the value for core_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_sex
     *
     * @return the value of core_user.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_sex
     *
     * @param userSex the value for core_user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_married
     *
     * @return the value of core_user.user_married
     *
     * @mbggenerated
     */
    public Integer getUserMarried() {
        return userMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_married
     *
     * @param userMarried the value for core_user.user_married
     *
     * @mbggenerated
     */
    public void setUserMarried(Integer userMarried) {
        this.userMarried = userMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_id_no
     *
     * @return the value of core_user.user_id_no
     *
     * @mbggenerated
     */
    public String getUserIdNo() {
        return userIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_id_no
     *
     * @param userIdNo the value for core_user.user_id_no
     *
     * @mbggenerated
     */
    public void setUserIdNo(String userIdNo) {
        this.userIdNo = userIdNo == null ? null : userIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_phone
     *
     * @return the value of core_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_phone
     *
     * @param userPhone the value for core_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_second_phone
     *
     * @return the value of core_user.user_second_phone
     *
     * @mbggenerated
     */
    public String getUserSecondPhone() {
        return userSecondPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_second_phone
     *
     * @param userSecondPhone the value for core_user.user_second_phone
     *
     * @mbggenerated
     */
    public void setUserSecondPhone(String userSecondPhone) {
        this.userSecondPhone = userSecondPhone == null ? null : userSecondPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_urgent_phone
     *
     * @return the value of core_user.user_urgent_phone
     *
     * @mbggenerated
     */
    public String getUserUrgentPhone() {
        return userUrgentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_urgent_phone
     *
     * @param userUrgentPhone the value for core_user.user_urgent_phone
     *
     * @mbggenerated
     */
    public void setUserUrgentPhone(String userUrgentPhone) {
        this.userUrgentPhone = userUrgentPhone == null ? null : userUrgentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_password
     *
     * @return the value of core_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_password
     *
     * @param userPassword the value for core_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_create_time
     *
     * @return the value of core_user.user_create_time
     *
     * @mbggenerated
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_create_time
     *
     * @param userCreateTime the value for core_user.user_create_time
     *
     * @mbggenerated
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_update_time
     *
     * @return the value of core_user.user_update_time
     *
     * @mbggenerated
     */
    public Date getUserUpdateTime() {
        return userUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_update_time
     *
     * @param userUpdateTime the value for core_user.user_update_time
     *
     * @mbggenerated
     */
    public void setUserUpdateTime(Date userUpdateTime) {
        this.userUpdateTime = userUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_comment
     *
     * @return the value of core_user.user_comment
     *
     * @mbggenerated
     */
    public String getUserComment() {
        return userComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_comment
     *
     * @param userComment the value for core_user.user_comment
     *
     * @mbggenerated
     */
    public void setUserComment(String userComment) {
        this.userComment = userComment == null ? null : userComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_status
     *
     * @return the value of core_user.user_status
     *
     * @mbggenerated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_status
     *
     * @param userStatus the value for core_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_user.user_deleted
     *
     * @return the value of core_user.user_deleted
     *
     * @mbggenerated
     */
    public Integer getUserDeleted() {
        return userDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_user.user_deleted
     *
     * @param userDeleted the value for core_user.user_deleted
     *
     * @mbggenerated
     */
    public void setUserDeleted(Integer userDeleted) {
        this.userDeleted = userDeleted;
    }
}