package com.blueseaheart.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CoreUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core_user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public CoreUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNull() {
            addCriterion("user_sex is null");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNotNull() {
            addCriterion("user_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUserSexEqualTo(Integer value) {
            addCriterion("user_sex =", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotEqualTo(Integer value) {
            addCriterion("user_sex <>", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThan(Integer value) {
            addCriterion("user_sex >", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_sex >=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThan(Integer value) {
            addCriterion("user_sex <", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThanOrEqualTo(Integer value) {
            addCriterion("user_sex <=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexIn(List<Integer> values) {
            addCriterion("user_sex in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotIn(List<Integer> values) {
            addCriterion("user_sex not in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexBetween(Integer value1, Integer value2) {
            addCriterion("user_sex between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotBetween(Integer value1, Integer value2) {
            addCriterion("user_sex not between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserMarriedIsNull() {
            addCriterion("user_married is null");
            return (Criteria) this;
        }

        public Criteria andUserMarriedIsNotNull() {
            addCriterion("user_married is not null");
            return (Criteria) this;
        }

        public Criteria andUserMarriedEqualTo(Integer value) {
            addCriterion("user_married =", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedNotEqualTo(Integer value) {
            addCriterion("user_married <>", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedGreaterThan(Integer value) {
            addCriterion("user_married >", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_married >=", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedLessThan(Integer value) {
            addCriterion("user_married <", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedLessThanOrEqualTo(Integer value) {
            addCriterion("user_married <=", value, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedIn(List<Integer> values) {
            addCriterion("user_married in", values, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedNotIn(List<Integer> values) {
            addCriterion("user_married not in", values, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedBetween(Integer value1, Integer value2) {
            addCriterion("user_married between", value1, value2, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserMarriedNotBetween(Integer value1, Integer value2) {
            addCriterion("user_married not between", value1, value2, "userMarried");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIsNull() {
            addCriterion("user_id_no is null");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIsNotNull() {
            addCriterion("user_id_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdNoEqualTo(String value) {
            addCriterion("user_id_no =", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotEqualTo(String value) {
            addCriterion("user_id_no <>", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoGreaterThan(String value) {
            addCriterion("user_id_no >", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_id_no >=", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLessThan(String value) {
            addCriterion("user_id_no <", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLessThanOrEqualTo(String value) {
            addCriterion("user_id_no <=", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLike(String value) {
            addCriterion("user_id_no like", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotLike(String value) {
            addCriterion("user_id_no not like", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIn(List<String> values) {
            addCriterion("user_id_no in", values, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotIn(List<String> values) {
            addCriterion("user_id_no not in", values, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoBetween(String value1, String value2) {
            addCriterion("user_id_no between", value1, value2, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotBetween(String value1, String value2) {
            addCriterion("user_id_no not between", value1, value2, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneIsNull() {
            addCriterion("user_second_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneIsNotNull() {
            addCriterion("user_second_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneEqualTo(String value) {
            addCriterion("user_second_phone =", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneNotEqualTo(String value) {
            addCriterion("user_second_phone <>", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneGreaterThan(String value) {
            addCriterion("user_second_phone >", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_second_phone >=", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneLessThan(String value) {
            addCriterion("user_second_phone <", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_second_phone <=", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneLike(String value) {
            addCriterion("user_second_phone like", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneNotLike(String value) {
            addCriterion("user_second_phone not like", value, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneIn(List<String> values) {
            addCriterion("user_second_phone in", values, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneNotIn(List<String> values) {
            addCriterion("user_second_phone not in", values, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneBetween(String value1, String value2) {
            addCriterion("user_second_phone between", value1, value2, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserSecondPhoneNotBetween(String value1, String value2) {
            addCriterion("user_second_phone not between", value1, value2, "userSecondPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneIsNull() {
            addCriterion("user_urgent_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneIsNotNull() {
            addCriterion("user_urgent_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneEqualTo(String value) {
            addCriterion("user_urgent_phone =", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneNotEqualTo(String value) {
            addCriterion("user_urgent_phone <>", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneGreaterThan(String value) {
            addCriterion("user_urgent_phone >", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_urgent_phone >=", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneLessThan(String value) {
            addCriterion("user_urgent_phone <", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_urgent_phone <=", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneLike(String value) {
            addCriterion("user_urgent_phone like", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneNotLike(String value) {
            addCriterion("user_urgent_phone not like", value, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneIn(List<String> values) {
            addCriterion("user_urgent_phone in", values, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneNotIn(List<String> values) {
            addCriterion("user_urgent_phone not in", values, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneBetween(String value1, String value2) {
            addCriterion("user_urgent_phone between", value1, value2, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserUrgentPhoneNotBetween(String value1, String value2) {
            addCriterion("user_urgent_phone not between", value1, value2, "userUrgentPhone");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNull() {
            addCriterion("user_create_time is null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIsNotNull() {
            addCriterion("user_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeEqualTo(Date value) {
            addCriterion("user_create_time =", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotEqualTo(Date value) {
            addCriterion("user_create_time <>", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThan(Date value) {
            addCriterion("user_create_time >", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_create_time >=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThan(Date value) {
            addCriterion("user_create_time <", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_create_time <=", value, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeIn(List<Date> values) {
            addCriterion("user_create_time in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotIn(List<Date> values) {
            addCriterion("user_create_time not in", values, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeBetween(Date value1, Date value2) {
            addCriterion("user_create_time between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_create_time not between", value1, value2, "userCreateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIsNull() {
            addCriterion("user_update_time is null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIsNotNull() {
            addCriterion("user_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeEqualTo(Date value) {
            addCriterion("user_update_time =", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotEqualTo(Date value) {
            addCriterion("user_update_time <>", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeGreaterThan(Date value) {
            addCriterion("user_update_time >", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_update_time >=", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeLessThan(Date value) {
            addCriterion("user_update_time <", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_update_time <=", value, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeIn(List<Date> values) {
            addCriterion("user_update_time in", values, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotIn(List<Date> values) {
            addCriterion("user_update_time not in", values, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("user_update_time between", value1, value2, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_update_time not between", value1, value2, "userUpdateTime");
            return (Criteria) this;
        }

        public Criteria andUserCommentIsNull() {
            addCriterion("user_comment is null");
            return (Criteria) this;
        }

        public Criteria andUserCommentIsNotNull() {
            addCriterion("user_comment is not null");
            return (Criteria) this;
        }

        public Criteria andUserCommentEqualTo(String value) {
            addCriterion("user_comment =", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotEqualTo(String value) {
            addCriterion("user_comment <>", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentGreaterThan(String value) {
            addCriterion("user_comment >", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentGreaterThanOrEqualTo(String value) {
            addCriterion("user_comment >=", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLessThan(String value) {
            addCriterion("user_comment <", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLessThanOrEqualTo(String value) {
            addCriterion("user_comment <=", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLike(String value) {
            addCriterion("user_comment like", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotLike(String value) {
            addCriterion("user_comment not like", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentIn(List<String> values) {
            addCriterion("user_comment in", values, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotIn(List<String> values) {
            addCriterion("user_comment not in", values, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentBetween(String value1, String value2) {
            addCriterion("user_comment between", value1, value2, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotBetween(String value1, String value2) {
            addCriterion("user_comment not between", value1, value2, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Integer value) {
            addCriterion("user_status =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Integer value) {
            addCriterion("user_status <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Integer value) {
            addCriterion("user_status >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_status >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Integer value) {
            addCriterion("user_status <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Integer value) {
            addCriterion("user_status <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Integer> values) {
            addCriterion("user_status in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Integer> values) {
            addCriterion("user_status not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Integer value1, Integer value2) {
            addCriterion("user_status between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("user_status not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserDeletedIsNull() {
            addCriterion("user_deleted is null");
            return (Criteria) this;
        }

        public Criteria andUserDeletedIsNotNull() {
            addCriterion("user_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andUserDeletedEqualTo(Integer value) {
            addCriterion("user_deleted =", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedNotEqualTo(Integer value) {
            addCriterion("user_deleted <>", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedGreaterThan(Integer value) {
            addCriterion("user_deleted >", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_deleted >=", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedLessThan(Integer value) {
            addCriterion("user_deleted <", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("user_deleted <=", value, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedIn(List<Integer> values) {
            addCriterion("user_deleted in", values, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedNotIn(List<Integer> values) {
            addCriterion("user_deleted not in", values, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedBetween(Integer value1, Integer value2) {
            addCriterion("user_deleted between", value1, value2, "userDeleted");
            return (Criteria) this;
        }

        public Criteria andUserDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("user_deleted not between", value1, value2, "userDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core_user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}