package com.blueseaheart.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PKECHxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public PKECHxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHxIdIsNull() {
            addCriterion("hx_id is null");
            return (Criteria) this;
        }

        public Criteria andHxIdIsNotNull() {
            addCriterion("hx_id is not null");
            return (Criteria) this;
        }

        public Criteria andHxIdEqualTo(Integer value) {
            addCriterion("hx_id =", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdNotEqualTo(Integer value) {
            addCriterion("hx_id <>", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdGreaterThan(Integer value) {
            addCriterion("hx_id >", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hx_id >=", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdLessThan(Integer value) {
            addCriterion("hx_id <", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdLessThanOrEqualTo(Integer value) {
            addCriterion("hx_id <=", value, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdIn(List<Integer> values) {
            addCriterion("hx_id in", values, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdNotIn(List<Integer> values) {
            addCriterion("hx_id not in", values, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdBetween(Integer value1, Integer value2) {
            addCriterion("hx_id between", value1, value2, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hx_id not between", value1, value2, "hxId");
            return (Criteria) this;
        }

        public Criteria andHxUsernameIsNull() {
            addCriterion("hx_username is null");
            return (Criteria) this;
        }

        public Criteria andHxUsernameIsNotNull() {
            addCriterion("hx_username is not null");
            return (Criteria) this;
        }

        public Criteria andHxUsernameEqualTo(String value) {
            addCriterion("hx_username =", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameNotEqualTo(String value) {
            addCriterion("hx_username <>", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameGreaterThan(String value) {
            addCriterion("hx_username >", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("hx_username >=", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameLessThan(String value) {
            addCriterion("hx_username <", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameLessThanOrEqualTo(String value) {
            addCriterion("hx_username <=", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameLike(String value) {
            addCriterion("hx_username like", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameNotLike(String value) {
            addCriterion("hx_username not like", value, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameIn(List<String> values) {
            addCriterion("hx_username in", values, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameNotIn(List<String> values) {
            addCriterion("hx_username not in", values, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameBetween(String value1, String value2) {
            addCriterion("hx_username between", value1, value2, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxUsernameNotBetween(String value1, String value2) {
            addCriterion("hx_username not between", value1, value2, "hxUsername");
            return (Criteria) this;
        }

        public Criteria andHxPasswordIsNull() {
            addCriterion("hx_password is null");
            return (Criteria) this;
        }

        public Criteria andHxPasswordIsNotNull() {
            addCriterion("hx_password is not null");
            return (Criteria) this;
        }

        public Criteria andHxPasswordEqualTo(String value) {
            addCriterion("hx_password =", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordNotEqualTo(String value) {
            addCriterion("hx_password <>", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordGreaterThan(String value) {
            addCriterion("hx_password >", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("hx_password >=", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordLessThan(String value) {
            addCriterion("hx_password <", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordLessThanOrEqualTo(String value) {
            addCriterion("hx_password <=", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordLike(String value) {
            addCriterion("hx_password like", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordNotLike(String value) {
            addCriterion("hx_password not like", value, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordIn(List<String> values) {
            addCriterion("hx_password in", values, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordNotIn(List<String> values) {
            addCriterion("hx_password not in", values, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordBetween(String value1, String value2) {
            addCriterion("hx_password between", value1, value2, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxPasswordNotBetween(String value1, String value2) {
            addCriterion("hx_password not between", value1, value2, "hxPassword");
            return (Criteria) this;
        }

        public Criteria andHxNicknameIsNull() {
            addCriterion("hx_nickname is null");
            return (Criteria) this;
        }

        public Criteria andHxNicknameIsNotNull() {
            addCriterion("hx_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andHxNicknameEqualTo(String value) {
            addCriterion("hx_nickname =", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameNotEqualTo(String value) {
            addCriterion("hx_nickname <>", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameGreaterThan(String value) {
            addCriterion("hx_nickname >", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("hx_nickname >=", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameLessThan(String value) {
            addCriterion("hx_nickname <", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameLessThanOrEqualTo(String value) {
            addCriterion("hx_nickname <=", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameLike(String value) {
            addCriterion("hx_nickname like", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameNotLike(String value) {
            addCriterion("hx_nickname not like", value, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameIn(List<String> values) {
            addCriterion("hx_nickname in", values, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameNotIn(List<String> values) {
            addCriterion("hx_nickname not in", values, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameBetween(String value1, String value2) {
            addCriterion("hx_nickname between", value1, value2, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxNicknameNotBetween(String value1, String value2) {
            addCriterion("hx_nickname not between", value1, value2, "hxNickname");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridIsNull() {
            addCriterion("hx_pkecUserId is null");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridIsNotNull() {
            addCriterion("hx_pkecUserId is not null");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridEqualTo(Integer value) {
            addCriterion("hx_pkecUserId =", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridNotEqualTo(Integer value) {
            addCriterion("hx_pkecUserId <>", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridGreaterThan(Integer value) {
            addCriterion("hx_pkecUserId >", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("hx_pkecUserId >=", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridLessThan(Integer value) {
            addCriterion("hx_pkecUserId <", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridLessThanOrEqualTo(Integer value) {
            addCriterion("hx_pkecUserId <=", value, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridIn(List<Integer> values) {
            addCriterion("hx_pkecUserId in", values, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridNotIn(List<Integer> values) {
            addCriterion("hx_pkecUserId not in", values, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridBetween(Integer value1, Integer value2) {
            addCriterion("hx_pkecUserId between", value1, value2, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxPkecuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("hx_pkecUserId not between", value1, value2, "hxPkecuserid");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeIsNull() {
            addCriterion("hx_userType is null");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeIsNotNull() {
            addCriterion("hx_userType is not null");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeEqualTo(String value) {
            addCriterion("hx_userType =", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeNotEqualTo(String value) {
            addCriterion("hx_userType <>", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeGreaterThan(String value) {
            addCriterion("hx_userType >", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeGreaterThanOrEqualTo(String value) {
            addCriterion("hx_userType >=", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeLessThan(String value) {
            addCriterion("hx_userType <", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeLessThanOrEqualTo(String value) {
            addCriterion("hx_userType <=", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeLike(String value) {
            addCriterion("hx_userType like", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeNotLike(String value) {
            addCriterion("hx_userType not like", value, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeIn(List<String> values) {
            addCriterion("hx_userType in", values, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeNotIn(List<String> values) {
            addCriterion("hx_userType not in", values, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeBetween(String value1, String value2) {
            addCriterion("hx_userType between", value1, value2, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxUsertypeNotBetween(String value1, String value2) {
            addCriterion("hx_userType not between", value1, value2, "hxUsertype");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateIsNull() {
            addCriterion("hx_createDate is null");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateIsNotNull() {
            addCriterion("hx_createDate is not null");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateEqualTo(Date value) {
            addCriterion("hx_createDate =", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateNotEqualTo(Date value) {
            addCriterion("hx_createDate <>", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateGreaterThan(Date value) {
            addCriterion("hx_createDate >", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("hx_createDate >=", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateLessThan(Date value) {
            addCriterion("hx_createDate <", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("hx_createDate <=", value, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateIn(List<Date> values) {
            addCriterion("hx_createDate in", values, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateNotIn(List<Date> values) {
            addCriterion("hx_createDate not in", values, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateBetween(Date value1, Date value2) {
            addCriterion("hx_createDate between", value1, value2, "hxCreatedate");
            return (Criteria) this;
        }

        public Criteria andHxCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("hx_createDate not between", value1, value2, "hxCreatedate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pkec_hx
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pkec_hx
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}