package com.blueseaheart.core.domain;

import java.util.Date;

public class PKECHx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_id
     *
     * @mbggenerated
     */
    private Integer hxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_username
     *
     * @mbggenerated
     */
    private String hxUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_password
     *
     * @mbggenerated
     */
    private String hxPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_nickname
     *
     * @mbggenerated
     */
    private String hxNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_pkecUserId
     *
     * @mbggenerated
     */
    private Integer hxPkecuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_userType
     *
     * @mbggenerated
     */
    private String hxUsertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pkec_hx.hx_createDate
     *
     * @mbggenerated
     */
    private Date hxCreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_id
     *
     * @return the value of pkec_hx.hx_id
     *
     * @mbggenerated
     */
    public Integer getHxId() {
        return hxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_id
     *
     * @param hxId the value for pkec_hx.hx_id
     *
     * @mbggenerated
     */
    public void setHxId(Integer hxId) {
        this.hxId = hxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_username
     *
     * @return the value of pkec_hx.hx_username
     *
     * @mbggenerated
     */
    public String getHxUsername() {
        return hxUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_username
     *
     * @param hxUsername the value for pkec_hx.hx_username
     *
     * @mbggenerated
     */
    public void setHxUsername(String hxUsername) {
        this.hxUsername = hxUsername == null ? null : hxUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_password
     *
     * @return the value of pkec_hx.hx_password
     *
     * @mbggenerated
     */
    public String getHxPassword() {
        return hxPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_password
     *
     * @param hxPassword the value for pkec_hx.hx_password
     *
     * @mbggenerated
     */
    public void setHxPassword(String hxPassword) {
        this.hxPassword = hxPassword == null ? null : hxPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_nickname
     *
     * @return the value of pkec_hx.hx_nickname
     *
     * @mbggenerated
     */
    public String getHxNickname() {
        return hxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_nickname
     *
     * @param hxNickname the value for pkec_hx.hx_nickname
     *
     * @mbggenerated
     */
    public void setHxNickname(String hxNickname) {
        this.hxNickname = hxNickname == null ? null : hxNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_pkecUserId
     *
     * @return the value of pkec_hx.hx_pkecUserId
     *
     * @mbggenerated
     */
    public Integer getHxPkecuserid() {
        return hxPkecuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_pkecUserId
     *
     * @param hxPkecuserid the value for pkec_hx.hx_pkecUserId
     *
     * @mbggenerated
     */
    public void setHxPkecuserid(Integer hxPkecuserid) {
        this.hxPkecuserid = hxPkecuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_userType
     *
     * @return the value of pkec_hx.hx_userType
     *
     * @mbggenerated
     */
    public String getHxUsertype() {
        return hxUsertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_userType
     *
     * @param hxUsertype the value for pkec_hx.hx_userType
     *
     * @mbggenerated
     */
    public void setHxUsertype(String hxUsertype) {
        this.hxUsertype = hxUsertype == null ? null : hxUsertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pkec_hx.hx_createDate
     *
     * @return the value of pkec_hx.hx_createDate
     *
     * @mbggenerated
     */
    public Date getHxCreatedate() {
        return hxCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pkec_hx.hx_createDate
     *
     * @param hxCreatedate the value for pkec_hx.hx_createDate
     *
     * @mbggenerated
     */
    public void setHxCreatedate(Date hxCreatedate) {
        this.hxCreatedate = hxCreatedate;
    }
}